#! /usr/bin/env bash
set -e

# select the path to clean
cleardir=$(pwd)

project_list=$(ls -d ${cleardir}/*)

for project in $project_list

do
   # rust
   rm -rf ${project}/target
   # nodejs/javascript/typescript
   rm -rf ${project}/node_modules
   # python
   rm -rf ${project}.virtualenvs
done